replicaCount: 1
subset: v1
image:
  repository: docker.io/fintechinnovation
  name: sre-coding-challenge-service-b
  tag: latest
  pullPolicy: Always

label:
  app: service-b

securityContext:
  runAsUser: 1000
  fsGroup: 1000

readinessProbe:
  enabled: true
  httpPath: "/healthz"

resources:
  requests:
    cpu: "0.03"
    memory: "64Mi"
  limits:
    cpu: "0.5"
    memory: "100Mi"

service:
  enabled: true
  port: 8888
  portName: http


networkPolicy:
  enabled: true
  applyToLabels:
    app: service-b
  ingress:
    - protocol: TCP
      port: 8888
      selectors:
        - app: service-a
